### ISSUE TITLE
ISO3 to region name mapping

### ISSUE THREAD

**Issue by Tinkaa** [OCHA-DAP/pa-aa-toolbox#109]
Several data sources are regional. So far we got USGS and FEWS NET and more might be added in the future. 

Currently the user has to add the relevant region names to the config. 

I am wondering if
1) some already curated mapping of iso3's to regions exists. If so, we could maybe use that and possibly make some custom adjustments if the data sources use different boundaries? 
2) if not, could we align somehow the namings of the different data sources, as now for many countries the USGS and FEWS NET name are the same. 

This is not urgent and not sure if even worth the effort, but it would make usage easier. What are your thoughts?

**Comment by caldwellst** [comment]
Was thinking the same! I think this is 100% worth the effort, where we just put a quick mapping of ISO3 codes to different regions for a data source (or multiple), so the user doesn't have to input it. Thus, if I put SOM, it should already know it's `east-africa`. Since these are relatively stable, should be something we can maintain?

There's definitely curated mappings of ISO3 to regions. Here's an R package I built at WHO to deal with that + some other issues of standardizing country data: [whoville](https://github.com/gpw13/whoville). However, the reason we needed the package was the different regions are extremely variable: SDG regions, SDG subregions, WHO regions, UN regions, World Bank regions, and so on. Might be worth it if we just did manual mapping for the data sources we are looking into?

**Comment by turnerm** [comment]
In my mind, the country config files are supposed to solve this problem for the datasets themselves-- we just need to implement them for all (or at least more) countries. This way an external user shouldn't really need to do anything.

For more general region mapping, I think Mike has already implemented some in [HDX Python Country](https://github.com/OCHA-DAP/hdx-python-country#:~:text=The%20HDX%20Python%20Country%20Library,one%20names%20from%20different%20sources.)

**Comment by Tinkaa** [comment]
Yeah actually you are right. Nvm then :)

**Comment by Tinkaa** [comment]
Oops sorry Seth, I totally missed you commented as well! I wasnt ignoring you. 

But I think in the end we all agree that it is probably hard to do it automatically due to different definitoins of regions. And we could best just do manual mapping by using the configs right? E.g. for FEWS NET there is around 40 countries so we might just add configs for all of them? 

Do you think that would work for NDVI as well @caldwellst ?

**Comment by caldwellst** [comment]
Yeah, exactly, I think we can just do that! Shouldn't be too hard for NDVI either. And no worries, didn't feel ignored since I think we all agree!
