### ISSUE TITLE
Standardizing input dates

### ISSUE THREAD

**Issue by turnerm** [OCHA-DAP/pa-aa-toolbox#128]
I couldn't find the discussion on Slack, but iirc we wanted to talk about the standardization of input dates, seeing as most data sources require one type of date or another as input. 

For the sake of this discussion (and simplicity), I would say try to stick to our own use cases - we can always add / modify if others come up. I think our main use case involves downloading historical data over several years, often the full range of what's available. 

Thus, I will propose a couple of options for `start_date` and `end_date` parameters (with the default set to the range of what's available for the data source):

1. Passing in just the year as an int or str. The advantage is that it's very simple. However, the downside is that you lose any date / month flexibility, and it seems a bit rigid as a paradigm for all (future) data sources. 

2. A Python `date` object. While it's a bit annoying to create such an object, we are probably not using the parameter that often anyway. And it does give some flexibility if needed. 

FEWS NET is a special case -- if we use option 1 then it can stay the same, with option 2 maybe it can just take the year / month and ignore the day number of the `date` object. @Tinkaa what are your thoughts?

If we go with 2, we could also support ISO 8601 format as @caldwellst did for NDVI, but we should perhaps write some utils for that if we're going to use it across data sources.

**Comment by caldwellst** [comment]
Hey @turnerm, thanks for starting the discussion! Sorry, my time for toolbox got eaten up last week and haven't had time to return to it yet.

My initial thought would be to go with the second option as a *baseline*. So all implementations have input dates based on `start_date` and `end_date`, where ISO8601 strings and `date` objects are passed in. I put in a `_dates` module in the NDVI PR that could easily have functions to deal with this (split off from the current dekadal functionality). However, as you mention, there are special cases for case 2. NDVI just needs years/dekads, so it requires conversion to that format. FEWSNET from @Tinkaa and monthly CHIRPS from @castledan require years/months. So I think allowing those additional inputs as tuples would make sense.

I think the flexibility makes sense, because at least in the case of dekads, it's much easier to just say the 1st of a month or some other date rather than calculating the dekad yourself. And my doing the conversion on the backend through the toolbox it again allows a single date to be passed to all methods, even if each of them might allow a specific tuple format to also be passed in. Let me know what y'all think!

**Comment by caldwellst** [comment]
Just to add for option 1, because left unsaid up above, for data like NDVI or other large rasters, enforcing year downloads and processing can take a lot of time, so probably best to avoid that if we can.

**Comment by castledan** [comment]
Can I suggest a third option?
- Start year, start month (optional) and start day (optional) and same for the end date
I think this would give maximum flexibility to the user.

**Comment by caldwellst** [comment]
I think the reasons I don't like that third option are:

- There's a lot of back end testing and validation we have to do against the various options to make sure they are all passed correctly. This could be avoided if, for start year and start month, for instance, you just require they are passed as a tuple.
- If users are required to pass all three, it would be a strange decision decision in my opinion to require passing 6 separate kwargs rather than just 2 that use a `date` object, which is designed to represent exactly that.
- It doesn't leave flexibility in the cases where dates are not in that format. Seasonal forecasts that are quarterly (not sure how you'd represent but likely would want flexibility), dekadal data, pentadal data. All of these we are losing flexibility in terms of passing directly the start and end dates in those formats.

**Comment by castledan** [comment]
I see your points, and I think the decision should depend on which users we have in mind. If these users are comfortable with Python, then the `date` object is probably a good choice, otherwise I'm not sure about it. More in detail on your points:

- I agree there's quite a lot of testing and validation to be done, but we would have to do it only once. Also, I already implemented part of it in Chirps. I think that the effort of doing this once is still incomparable respect to the effort that potential users would have to do every single time. I agree with the point of using tuples instead.
- The decision between using `date` objects or tuples should be made depending on the users we have in mind.
- I agree with the lack of flexibility in those cases, but is that not the same with the other two options?

**Comment by caldwellst** [comment]
So, the flexibility I was thinking of was that having `start_date` and `end_date` for each implementation would allow users to always input an ISO8601 date string or `date` object. Then, for specific methods, additional types of objects can be passed through. So, tuple of year/month for CHIRPS as you implemented or tuple year/dekad for NDVI like I implemented. Basically the flexibility of what user can pass in is there, it's just always passed to `start_date` and `end_date` so that the API is clean and easy to use. 

Basically, I agree with your approach that you don't want to force users to have to input more of a date than necessary, think that it's just slightly more flexible/cleaner if we use the base implementation of string/`date` that can be expanded to tuples or other use cases depending on the data. So my thought is that is why it is more flexible, because `start_date` can ostensibly accept any format that we decide (obviously should be well thought out), whereas by having `start_year`, `start_month`, `start_day`, we don't have that flexibility.

**Comment by Tinkaa** [comment]
I would agree with Seth's idea. Would definitely allow users to also pass a date string. I think that solves the issue of usability. At same time agree that with e.g. dekadal data we should keep the flexibillity as well to input the dekad. Have been experimenting a bit with Seth's NDVI implementation and to me that works very well.

**Comment by castledan** [comment]
Thanks for your explanation Seth, now it's clear to me what you're suggesting. And I agree with it, it looks like the cleanest solution!

**Comment by turnerm** [comment]
Thanks so much for the great discussion everyone. I think Seth said it well that whatever we choose should be our baseline, and then add other options as needed depending on the source. And I agree that #2 makes the most sense. 

Last point though: Do we want our current baseline to just be the `date` object, or also include the ISO 8610-formatted date string? My only concern is that supporting the latter isn't strictly needed at the moment for our use cases, and will take a (small) bit of work to generalize. Maybe I can make an issue to do so for the near future?

**Comment by caldwellst** [comment]
Maybe for now it's just initially switching those classes not in this format to accept a `date` object. Trying to start on NDVI today again, so once that is merged, I am happy to work on a very small PR to convert the stuff in the `_dates.py` module into having a generic function that accepts either a string or `date` which can be used across other implementations?

**Comment by castledan** [comment]
So, if I understand correctly, the Chirps class should accept two `date`objects (start and end date). And what if the user wants to specify only the year or the year and the month?

**Comment by caldwellst** [comment]
Not sure if this is best approach, but I made this `utils` module that basically dealt with the 3 options.

https://github.com/OCHA-DAP/pa-aa-toolbox/blob/ndvi/src/aatoolbox/utils/_dates.py

**Comment by turnerm** [comment]
> I am happy to work on a very small PR to convert the stuff in the _dates.py module into having a generic function that accepts either a string or date which can be used across other implementations?

@caldwellst that would be great! I made #129 

> Not sure if this is best approach, but I made this utils module that basically dealt with the 3 options, which would be similar for CHIRPS just instead of year/dekad tuple, year/month tuple.

Not sure if the year-month case could be simplified by just using a built-in `date` object with the date set to 1 or something.

> So, if I understand correctly, the Chirps class should accept two dateobjects (start and end date). And what if the user wants to specify only the year or the year and the month?

@castledan one can always use the date object to specify a range that covers exactly a year or set of months, it's just slightly more annoying to type out. But if you want to add the year-month case then Seth's suggestion is a good one.

**Comment by turnerm** [comment]
Closing because I think the issue was settled
